In [12]:
import pandas as pd
df = pd.read_csv("eurocup_2020_results.csv")
df.head()

,stage,date,pens,pens_home_score,pens_away_score,team_name_home,team_name_away,team_home_score,team_away_score,possession_home,possession_away,total_shots_home,total_shots_away,shots_on_target_home,shots_on_target_away,duels_won_home,duels_won_away,events_list,lineup_home,lineup_away
0,Final,11.07.2021,True,3,2,Italy,England,1,1,66%,34%,19,6,6,2,53%,47%,"[{'event_team': 'away', 'event_time': "" 2' "", ...","[{'Player_Name': 'Insigne', 'Player_Number': '...","[{'Player_Name': 'Kane', 'Player_Number': '9'}..."
1,Semi-finals,07.07.2021,False,False,False,England,Denmark,2,1,59%,41%,20,6,10,3,50%,50%,"[{'event_team': 'away', 'event_time': "" 30' "",...","[{'Player_Name': 'Kane', 'Player_Number': '9'}...","[{'Player_Name': 'Krogh Damsgaard', 'Player_Nu..."
2,Semi-finals,06.07.2021,True,4,2,Italy,Spain,1,1,29%,71%,7,16,4,5,49%,51%,"[{'event_team': 'away', 'event_time': "" 51' "",...","[{'Player_Name': 'Insigne', 'Player_Number': '...","[{'Player_Name': 'Torres', 'Player_Number': '1..."
3,Quarter-finals,03.07.2021,False,False,False,Ukraine,England,0,4,48%,52%,7,10,2,6,42%,59%,"[{'event_team': 'away', 'event_time': "" 4' "", ...","[{'Player_Name': 'Yaremchuk', 'Player_Number':...","[{'Player_Name': 'Kane', 'Player_Number': '9'}..."
4,Quarter-finals,03.07.2021,False,False,False,Czech Republic,Denmark,1,2,56%,44%,16,11,5,7,48%,52%,"[{'event_team': 'away', 'event_time': "" 5' "", ...","[{'Player_Name': 'Schick', 'Player_Number': '1...","[{'Player_Name': 'Dolberg', 'Player_Number': '..."

In [13]:
df.describe()

,team_home_score,team_away_score,total_shots_home,total_shots_away,shots_on_target_home,shots_on_target_away
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,1.196078,1.588235,12.137255,12.235294,3.803922,4.352941
std,1.077397,1.344269,6.190378,5.788223,2.545738,2.681966
min,0.000000,0.000000,3.000000,1.000000,0.000000,0.000000
25%,0.000000,1.000000,7.000000,8.500000,2.000000,2.000000
50%,1.000000,1.000000,11.000000,11.000000,4.000000,4.000000
75%,2.000000,2.000000,17.000000,16.000000,6.000000,6.500000
max,3.000000,5.000000,27.000000,28.000000,10.000000,10.000000

In [14]:
df.columns

Index(['stage', 'date', 'pens', 'pens_home_score', 'pens_away_score',
       'team_name_home', 'team_name_away', 'team_home_score',
       'team_away_score', 'possession_home', 'possession_away',
       'total_shots_home', 'total_shots_away', 'shots_on_target_home',
       'shots_on_target_away', 'duels_won_home', 'duels_won_away',
       'events_list', 'lineup_home', 'lineup_away'],
      dtype='object')

In [15]:
df['stage'].unique()

array([' Final ', ' Semi-finals ', ' Quarter-finals ', ' Round of 16 ',
       ' Group stage: Matchday 3 ', ' Group stage: Matchday 2 ',
       ' Group stage: Matchday 1 '], dtype=object)

In [21]:
#quitar el espacio y volverlo a meter en el dataset
def quitaespacios(campo):
    valor_trip = df[campo].str.strip()
    df[campo] = valor_trip
quitaespacios("stage")
quitaespacios("team_name_home")
quitaespacios("team_name_away")

df.to_csv("EurocopaLimpio.csv")

In [19]:
df['team_name_away'].unique()

array(['England', 'Denmark', 'Spain', 'Italy', 'Ukraine', 'Germany',
       'Switzerland', 'Portugal', 'Czech Republic', 'Austria', 'France',
       'Hungary', 'Poland', 'Scotland', 'Belgium', 'Netherlands', 'Wales',
       'Turkey', 'Slovakia', 'North Macedonia', 'Russia', 'Sweden',
       'Croatia', 'Finland'], dtype=object)

In [8]:
df['date'].unique()

array(['11.07.2021', ' 07.07.2021 ', '06.07.2021', ' 03.07.2021 ',
       ' 02.07.2021 ', '02.07.2021', ' 29.06.2021 ', '28.06.2021',
       ' 28.06.2021 ', ' 27.06.2021 ', ' 26.06.2021 ', ' 23.06.2021 ',
       ' 22.06.2021 ', ' 21.06.2021 ', ' 20.06.2021 ', ' 19.06.2021 ',
       ' 18.06.2021 ', ' 17.06.2021 ', ' 16.06.2021 ', ' 15.06.2021 ',
       ' 14.06.2021 ', ' 13.06.2021 ', ' 12.06.2021 ', ' 11.06.2021 '],
      dtype=object)

In [10]:
df['pens'].value_counts()

False    47
True      4
Name: pens, dtype: int64

In [31]:
df['pens_home_score', ]

0         3
1     False
2         4
3     False
4     False
5     False
6         1
7     False
8     False
9         4
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
Name: pens_home_score, dtype: object